// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: 2018年 5月28日 星期一 22时12分59秒 UTC

package main

import (
	// This Service
	"bookinfo/bookcomments-service/svc/server"
	"bookinfo/bookcomments-service/global"
)

func main() {

	global.GenPid(global.RuntimePath + "/pid")
	server.Run()
}
