service_name: book-comments
db_book:
  username: root
  pwd: root
  driver: mysql
  host: localhost
  port: 3306
  db_name: bookinfo
  charset: utf8
  local: Local
  parse_time: True
  conn_max_life_time: 3600
  max_idle_conns: 10
  max_open_conns: 1000
redis:
  addr: "127.0.0.1:6973"
  password: ""
  db: 0
zipkin:
  addr: http://localhost:9411
  service_name: book-comments
  reporter:
    timeout: 5
    batch_size: 1000
    batch_interval: 3
http_server:
  addr: :5011
grpc_server:
  addr: :5012
debug_server:
  addr: :5013
metrics_server:
  addr: :5014