service_name: book-details
db_book:
  username: root
  pwd: root
  host: mysql.server
  port: 3306
  db_name: bookinfo
  driver: mysql
  charset: utf8
  parse_time: True
  local: Local
  conn_max_life_time: 3600
  max_idle_conns: 10
  max_open_conns: 1000
redis:
  addr: "redis.server:6379"
  password: ""
  db: 0
zipkin:
  addr: http://zipkin:9411
  service_name: book-details
  reporter:
    timeout: 5
    batch_size: 1000
    batch_interval: 3
http_server:
  addr: :5001
grpc_server:
  addr: :5002
debug_server:
  addr: :5003
metrics_server:
  addr: :5004
servers:
  book_comments:
    grpc: books-comments:5012